services:
  scraper:
    image: ghcr.io/iamsoloma/web-scraper-api:0.0.8
    build: .
    networks:
      - scraper-network
    volumes:
       - ./config.yaml:/usr/bin/config.yaml:ro
    ports:
      - "8080:8080"

      
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: "tasks"
      POSTGRES_USER: "main"
      POSTGRES_PASSWORD: "qwerty"
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - scraper-network
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  seaweedfs:
    image: chrislusf/seaweedfs
    environment:
      AWS_ACCESS_KEY_ID: "main"
      AWS_SECRET_ACCESS_KEY: "qwerty"
      S3_BUCKET: "tasks"
    networks:
      - scraper-network
    volumes:
      - storagedata:/data
    ports:
      - "8333:8333"
      - "23646:23646"


volumes:
  pgdata:
  storagedata:

networks:
  scraper-network:
    driver: bridge

