services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: "tasks"
      POSTGRES_USER: "main"
      POSTGRES_PASSWORD: "qwerty"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  seaweedfs:
    image: chrislusf/seaweedfs
    environment:
      AWS_ACCESS_KEY_ID: "main"
      AWS_SECRET_ACCESS_KEY: "qwerty"
      S3_BUCKET: "tasks"
    volumes:
      - storagedata:/data
    ports:
      - "8333:8333"
      - "23646:23646"


volumes:
  pgdata:
  storagedata:
